In [1]:
import numpy as np

In [2]:
q_0 = np.matrix([[1],[0]])
q_1 = np.matrix([[0],[1]])
q_i = q_0 + q_1
q_x = q_0 - q_1
q_y = q_0 - q_1
q_z = q_0 - q_1

In [4]:
def for_loop():
    for i in [q_i,q_x,q_y,q_z]:
        mat = i
        return mat
    

In [7]:
sign_list = []
for i in [q_i,q_x,q_y,q_z]:
    for j in [q_i,q_x,q_y,q_z]:
        mat = np.kron(i,j)
        sign_list.append(mat)

In [8]:
sign_list

[matrix([[1],
         [1],
         [1],
         [1]]),
 matrix([[ 1],
         [-1],
         [ 1],
         [-1]]),
 matrix([[ 1],
         [-1],
         [ 1],
         [-1]]),
 matrix([[ 1],
         [-1],
         [ 1],
         [-1]]),
 matrix([[ 1],
         [ 1],
         [-1],
         [-1]]),
 matrix([[ 1],
         [-1],
         [-1],
         [ 1]]),
 matrix([[ 1],
         [-1],
         [-1],
         [ 1]]),
 matrix([[ 1],
         [-1],
         [-1],
         [ 1]]),
 matrix([[ 1],
         [ 1],
         [-1],
         [-1]]),
 matrix([[ 1],
         [-1],
         [-1],
         [ 1]]),
 matrix([[ 1],
         [-1],
         [-1],
         [ 1]]),
 matrix([[ 1],
         [-1],
         [-1],
         [ 1]]),
 matrix([[ 1],
         [ 1],
         [-1],
         [-1]]),
 matrix([[ 1],
         [-1],
         [-1],
         [ 1]]),
 matrix([[ 1],
         [-1],
         [-1],
         [ 1]]),
 matrix([[ 1],
         [-1],
         [-1],
         [ 1]])]